version: "3.9"
services:
  ripple:
    platform: linux/amd64
    container_name: ripple
    image: ripple-custom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
      - "5005:5005"
      - "6005:6005"
      - "6006:6006"
      - "6007:6007"
      - "51234:51234"
      - "51235:51235"
    volumes:
      - ./:/shared/