version: "3.9"
services:
  validator_1:
    platform: linux/amd64
    container_name: validator_1
    image: "xrpllabsofficial/xrpld"
    entrypoint: /bin/bash -c "sleep infinity"
    ports:
      - "8001:80"
      - "5005:5005"
      - "6005:6005"
      - "6006:6006"
      - "51235:51235"
    volumes:
      - ./:/shared/